version: '3'
services:
  elasticsearch: 
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.4'
    container_name: ${ELASTIC_CONTAINER_NAME}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT_EXTERNAL_API}:${ELASTIC_PORT_INTERNAL_API}
      - ${ELASTIC_PORT_EXTERNAL_CLUSTER}:${ELASTIC_PORT_INTERNAL_CLUSTER}
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: ${KIBANA_CONTAINER_NAME}
    networks:
      - web
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT_EXTERNAL}:${KIBANA_PORT_INTERNAL}
    labels:
      - traefik.frontend.rule=Host:${KIBANA_HOSTNAME}
      - traefik.frontend.auth.basic.usersFile=/kibanapass
      - traefik.frontend.port=${KIBANA_PORT_INTERNAL}
    environment:
      - ELASTICSEARCH_URL=http://${KIBANA_ELASTIC_HOST}:${ELASTIC_PORT_EXTERNAL_API}
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=${KIBANA_HOSTNAME}
  fluentd:
    image: registry.xirion.net/cshub/fluentd:latest 
    container_name: ${FLUENTD_CONTAINER_NAME}
    logging:
      driver: "json-file"
    ports:
     - ${FLUENTD_PORT_EXTERNAL}:${FLUENTD_PORT_INTERNAL}
     - ${FLUENTD_PORT_EXTERNAL}:${FLUENTD_PORT_INTERNAL}/udp
    volumes:
     - ./fluentd/conf:/fluentd/etc
volumes:
  esdata1:

networks:
  web:
    external: true

