matrix:
  include:
  - language: node_js
    env:
        - CLIENT=true
    node_js:
        - "8"
        - "10"
    before_script:
        - cd faq-site-client
    script:
        - npm install
        - npm run build

  - language: node_js
    env:
        - SERVER=true
    node_js:
        - "8"
        - "10"
    before_script:
        - cd faq-site-server/src/
        - cp settings_baseline.ts settings.ts
        - cd ..
    script:
        - npm install
        - tsc

cache:
    directories:
        - faq-site-client/node_modules
        - faq-site-server/node_modules
