# Development containers
version: '3'
services:
  frontend_dev:
    image: cshubnl/client:dev
    environment:
      - VUE_APP_API_URL=https://api-dev.cshub.nl
    ports:
      - "8080:80"
  backend_dev:
    image: cshubnl/server:dev
    env_file: cshub-server/settings.env
    ports:
      - "3001:3001"

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 180 --cleanup
