version: '3'
services:
  shared:
    image: cshubnl/shared:dev

  frontend:
    image: cshubnl/client:dev
    depends_on:
      - shared
    environment:
      - VUE_APP_API_URL=https://api-dev.cshub.nl
      - VUE_APP_DEBUG=true
    ports:
      - "8080:80"

  backend:
    image: cshubnl/server:dev
    depends_on:
      - shared
    env_file: cshub-server/settings.env
    ports:
      - "3000:3000"
