# Development containers
version: '3'
services:
  frontend:
    image: cshubnl/client:master
    networks:
      - web
    labels:
      - traefik.frontend.rule=Host:cshub.nl
    environment:
      - VUE_APP_API_URL=https://api.cshub.nl
    ports:
      - "8181:80"
  backend:
    networks:
      - web
    image: cshubnl/server:master
    env_file: ./settings.env
    labels:
      - traefik.frontend.rule=Host:api.cshub.nl
      - treafik.frontend.port=3000
    ports:
      - "3000:3000"

networks:
  web:
    external: true
