version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: cshub-portainer
    labels:
      - traefik.frontend.rule=Host:portainer.cshub.nl
      - treafik.frontend.port=9000
    networks:
      - web
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer

volumes:
  portainer_data:

networks:
  web:
    external: true
