version: '3'
services:
  traefik:
    image: traefik # The official Traefik docker image
    container_name: ${CONTAINER_NAME}
    command: --api --docker
    networks:
      - web
    ports:
      - ${PORT_EXTERNAL_HTTP}:${PORT_INTERNAL_HTTP}     # The HTTP port
      - ${PORT_EXTERNAL_UI}:${PORT_INTERNAL_UI} # The Web UI (enabled by --api)
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME}
      - traefik.frontend.auth.basic.usersFile=/traefikpass
      - traefik.port=${PORT_EXTERNAL_UI}
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ../logging/.htpasswd:/kibanapass
      - ./.htpasswd:/traefikpass
networks:
  web:
    external: true
